apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 1Gi                  # size of storage
  accessModes:
  - ReadWriteOnce                 # one Pod at a time
  persistentVolumeReclaimPolicy: Retain   # keep data even after PVC deleted
  storageClassName: demo-storage-class
  hostPath:
    path: /tmp/demo-pv-data       # minikube uses hostPath # In EKS      → uses EBS
