apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
  - ReadWriteOnce                 # must match PV access mode
  storageClassName: demo-storage-class   # must match PV storage class
  resources:
    requests:
      storage: 500Mi              # requesting 500MB from 1GB PV
