apiVersion: apps/v1
kind: Deployment
metadata:
  name: telecom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telecom-app
  template:
    metadata:
      labels:
        app: telecom-app
    spec:
      containers:
      - name: telecom-app
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config      # non-sensitive config
        - secretRef:
            name: app-secret      # sensitive config
